inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 18

# Offense count: 2
Style/Documentation:
  Exclude:
    - '**/*'

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 102
