ruby: &ruby
  image: carwow/ruby-ci:2.4.4

elasticsearch_container: &elasticsearch_container
  image: carwow/elasticsearch-ci:5.5.1

version: 2
jobs:
  bundle:
    working_directory: ~/zelastic
    docker:
      - *ruby
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-
      - run: |
          bundle config --local path vendor/bundle &&
          bundle check || bundle install --jobs=4 --retry=3
          bundle clean --force
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: [vendor/bundle]

  rubocop:
    working_directory: ~/zelastic
    docker:
      - *ruby
    steps:
      - checkout
      - restore_cache: { keys: ['bundle-{{ checkout "Gemfile.lock" }}'] }
      - run: bundle exec rubocop

  tests:
    working_directory: ~/zelastic
    docker:
      - *ruby
      - *elasticsearch_container
    steps:
      - checkout
      - restore_cache: { keys: ['bundle-{{ checkout "Gemfile.lock" }}'] }
      - run: |
          bundle exec rspec --pattern "**/*_spec.rb" --format "progress"

workflows:
  version: 2
  build:
    jobs:
      - bundle
      - rubocop:
          requires: [bundle]
      - tests:
          requires: [bundle]
